spring:
  application:
    name: healthconnect-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/healthconnectdb}
    username: ${DB_USERNAME:healthadmin}
    password: ${DB_PASSWORD:Health@123}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: HealthConnect
    version: 1.0.0