spring:
  application:
    name: healthconnect-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: HealthConnect
    version: 1.0.0