apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthconnect-ingress
  namespace: healthconnect
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: healthconnect-api
                port:
                  number: 80