apiVersion: v1
kind: Service
metadata:
  name: healthconnect-api
  namespace: healthconnect
spec:
  type: LoadBalancer
  selector:
    app: healthconnect-api
  ports:
    - port: 80
      targetPort: 8080